### ISSUE TITLE
이 토큰은 무엇을 의미하나요?

### ISSUE THREAD

**Issue by 2404589803** [deep-diver/hf-daily-paper-newsletter#6]
github.event.inputs.date

DSTACK_TOKEN

SOLAR_API_KEY

이 토큰은 무엇을 나타냅니까?

**Comment by deep-diver** [comment]
> DSTACK_TOKEN

it is a dstack cloud token which handles Korean translation on the cloud. If you don't want to include korean translation feature, you can completely disable translation-ko workflow.

> SOLAR_API_KEY

it is a SOLAR LLM API key provided by Upstage. Since the API is OpenAI's API compatible, you can complitely replace the endpoint with OpenAI's API endpoint.

**Comment by 2404589803** [comment]
thanks
